# ============================================
# GITHUB PUSH AGENT
# Commits and pushes your code to GitHub
# Run this manually when YOU decide to push
# ============================================

import os
import subprocess
from dotenv import load_dotenv

load_dotenv()

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_REPO_URL = os.getenv("GITHUB_REPO_URL")

# ── INJECT TOKEN INTO URL ────────────────────
# This allows pushing without password prompt
# Converts: https://github.com/user/repo.git
# Into:     https://TOKEN@github.com/user/repo.git
url_parts = GITHUB_REPO_URL.replace("https://", "")
AUTH_URL = f"https://{GITHUB_TOKEN}@{url_parts}"

def run_command(command, description):
    """Run a shell command and show result"""
    print(f"\n>> {description}...")
    result = subprocess.run(
        command,
        shell=True,
        capture_output=True,
        text=True
    )
    if result.stdout:
        print(result.stdout)
    if result.stderr:
        # stderr isn't always an error in git
        print(result.stderr)
    if result.returncode != 0:
        print(f"Warning: command exited with code {result.returncode}")
    return result

def push_to_github(commit_message="Agent pipeline update"):
    print("\n" + "="*50)
    print("GITHUB PUSH AGENT STARTING...")
    print("="*50)

    # Step 1: Initialize git if not already done
    if not os.path.exists(".git"):
        run_command("git init", "Initializing git repository")
        run_command(
            f'git remote add origin {AUTH_URL}',
            "Adding remote origin"
        )
    else:
        # Update remote URL with token (in case token changed)
        run_command(
            f'git remote set-url origin {AUTH_URL}',
            "Updating remote URL"
        )

    # Step 2: Create .gitignore
    gitignore_content = """
venv/
__pycache__/
*.pyc
.env
*.json
.pytest_cache/
outputs/
"""
    with open(".gitignore", "w") as f:
        f.write(gitignore_content)
    print(">> Created .gitignore")

    # Step 3: Create README
    readme_content = """# Todo App — Built by AI Agents

This project was automatically generated by a multi-agent AI pipeline.

## Agents Used
- **Planner Agent** — Created the project plan
- **Reviewer Agent** — Reviewed and approved the plan  
- **Developer Agent** — Wrote all the Python code
- **Tester Agent** — Wrote 5 pytest tests (all passing)
- **GitHub Push Agent** — Pushed this code to GitHub

## How to Run
```bash
python -m todo_app.src.main
```

## How to Test
```bash
pytest todo_app/tests/ -v
```

## Tech Stack
- Python 3.11
- JSON for data storage
- pytest for testing
- CrewAI for agent orchestration
- Groq API (free) for AI models
"""
    with open("README.md", "w", encoding="utf-8") as f:
        f.write(readme_content)
    print(">> Created README.md")

    # Step 4: Stage all files
    run_command("git add .", "Staging all files")

    # Step 5: Commit
    run_command(
        f'git commit -m "{commit_message}"',
        "Creating commit"
    )

    # Step 6: Push to GitHub
    run_command(
        "git push -u origin main --force",
        "Pushing to GitHub"
    )

    print("\n" + "="*50)
    print("CODE PUSHED TO GITHUB!")
    print(f"Visit: {GITHUB_REPO_URL.replace('.git', '')}")
    print("="*50)

# ── RUN ON YOUR COMMAND ──────────────────────
if __name__ == "__main__":
    print("\nGitHub Push Agent ready!")
    print("This will commit and push your todo app to GitHub.")
    confirm = input("\nType 'push' to confirm: ").strip().lower()

    if confirm == "push":
        message = input("Enter commit message (or press Enter for default): ").strip()
        if not message:
            message = "AI agents built todo app with passing tests"
        push_to_github(commit_message=message)
    else:
        print("Push cancelled.")